export const data = {
   "_embedded":{
      "events":[
         {
            "name":"Dead & Company",
            "type":"event",
            "id":"G5vzZp7bPbZO3",
            "test":false,
            "url":"http://www.cubuffs.com/deadandcompany",
            "locale":"en-us",
            "images":[
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_TABLET_LANDSCAPE_16_9.jpg",
                  "width":1024,
                  "height":576,
                  "fallback":false
               },
               {
                  "ratio":"4_3",
                  "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_CUSTOM.jpg",
                  "width":305,
                  "height":225,
                  "fallback":false
               },
               {
                  "ratio":"3_2",
                  "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_TABLET_LANDSCAPE_3_2.jpg",
                  "width":1024,
                  "height":683,
                  "fallback":false
               },
               {
                  "ratio":"3_2",
                  "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_RETINA_PORTRAIT_3_2.jpg",
                  "width":640,
                  "height":427,
                  "fallback":false
               },
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_EVENT_DETAIL_PAGE_16_9.jpg",
                  "width":205,
                  "height":115,
                  "fallback":false
               },
               {
                  "ratio":"3_2",
                  "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_ARTIST_PAGE_3_2.jpg",
                  "width":305,
                  "height":203,
                  "fallback":false
               },
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_RETINA_PORTRAIT_16_9.jpg",
                  "width":640,
                  "height":360,
                  "fallback":false
               },
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/c/fbc/b293c0ad-c904-4215-bc59-8d7f2414dfbc_106141_TABLET_LANDSCAPE_LARGE_16_9.jpg",
                  "width":2048,
                  "height":1152,
                  "fallback":true
               },
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_RECOMENDATION_16_9.jpg",
                  "width":100,
                  "height":56,
                  "fallback":false
               },
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_RETINA_LANDSCAPE_16_9.jpg",
                  "width":1136,
                  "height":639,
                  "fallback":false
               }
            ],
            "sales":{
               "public":{
                  "startDateTime":"2020-02-14T17:00:00Z",
                  "startTBD":false,
                  "endDateTime":"2020-07-11T00:30:00Z"
               }
            },
            "dates":{
               "start":{
                  "localDate":"2020-07-10",
                  "localTime":"18:30:00",
                  "dateTime":"2020-07-11T00:30:00Z",
                  "dateTBD":false,
                  "dateTBA":false,
                  "timeTBA":false,
                  "noSpecificTime":false
               },
               "timezone":"America/Denver",
               "status":{
                  "code":"cancelled"
               },
               "spanMultipleDays":false
            },
            "classifications":[
               {
                  "primary":true,
                  "segment":{
                     "id":"KZFzniwnSyZfZ7v7nJ",
                     "name":"Music"
                  },
                  "genre":{
                     "id":"KnvZfZ7vAeA",
                     "name":"Rock"
                  },
                  "subGenre":{
                     "id":"KZazBEonSMnZfZ7v6F1",
                     "name":"Pop"
                  },
                  "type":{
                     "id":"KZAyXgnZfZ7v7nI",
                     "name":"Undefined"
                  },
                  "subType":{
                     "id":"KZFzBErXgnZfZ7v7lJ",
                     "name":"Undefined"
                  },
                  "family":false
               }
            ],
            "promoter":{
               "id":"653",
               "name":"LIVE NATION MUSIC",
               "description":"LIVE NATION MUSIC / NTL / USA"
            },
            "promoters":[
               {
                  "id":"653",
                  "name":"LIVE NATION MUSIC",
                  "description":"LIVE NATION MUSIC / NTL / USA"
               },
               {
                  "id":"4576",
                  "name":"LIVE NATION 3PE EVENT",
                  "description":"LIVE NATION 3PE EVENT / NTL / USA"
               }
            ],
            "ageRestrictions":{
               "legalAgeEnforced":false
            },
            "_links":{
               "self":{
                  "href":"/discovery/v2/events/G5vzZp7bPbZO3?locale=en-us"
               },
               "attractions":[
                  {
                     "href":"/discovery/v2/attractions/K8vZ917KYU0?locale=en-us"
                  }
               ],
               "venues":[
                  {
                     "href":"/discovery/v2/venues/KovZpZA1EvaA?locale=en-us"
                  }
               ]
            },
            "_embedded":{
               "venues":[
                  {
                     "name":"Folsom Field",
                     "type":"venue",
                     "id":"KovZpZA1EvaA",
                     "test":false,
                     "url":"https://www.ticketmaster.com/folsom-field-tickets-boulder/venue/246251",
                     "locale":"en-us",
                     "postalCode":"80309",
                     "timezone":"America/Denver",
                     "city":{
                        "name":"Boulder"
                     },
                     "state":{
                        "name":"Colorado",
                        "stateCode":"CO"
                     },
                     "country":{
                        "name":"United States Of America",
                        "countryCode":"US"
                     },
                     "address":{
                        "line1":"Stadium Drive"
                     },
                     "location":{
                        "longitude":"-105.2664074",
                        "latitude":"40.0105103"
                     },
                     "markets":[
                        {
                           "name":"Denver and More",
                           "id":"6"
                        }
                     ],
                     "dmas":[
                        {
                           "id":248
                        },
                        {
                           "id":254
                        },
                        {
                           "id":264
                        },
                        {
                           "id":285
                        },
                        {
                           "id":347
                        }
                     ],
                     "boxOfficeInfo":{
                        "phoneNumberDetail":"CU Athletic Ticket Office: (800) 872-8337 or 303-492-8337 Alumni Tickets Call: (303) 492-8484 Family Weekend Call: (303) 492-1380",
                        "openHoursDetail":"8:30 a.m. – 4:30 p.m M-F Football gameday hours : Open 4 hours",
                        "acceptedPaymentDetail":"Cash, Visa, MasterCard, Discover, Checks",
                        "willCallDetail":"Will Call Windows are located at the Ticket Booth across the parking lot at the southeast corner of the stadium, between gates 4-5. Will Call is available 4 hours prior to kickoff."
                     },
                     "parkingDetail":"Parking Lots on campus close to the stadium are reserved for donors to the Buff Club and are controlled by the Athletic Dept. Contact the Buff Club at 303-492-2200 for info on donor parking. Public parking areas are also available on campus. These areas are controlled by University Parking Services. There is a per game charge for these lots and parking is on a first come, first served basis. Call 303-492-7384 or visit their web at http://ucbparking.colorado.edu for more info. Any illegally parked vehicles will be towed at the owner's expense.",
                     "accessibleSeatingDetail":"Accessible seating can be obtained by calling the CU Athletic Ticket Office at (800) 872-8337 or 303-492-8337.",
                     "generalInfo":{
                        "generalRule":"Alcohol is not permitted in Folsom Field or on stadium grounds. Individuals caught with alcoholic beverages will be removed from the stadium. Inebriated individuals will be denied admission to the stadium. Such ejections are not grounds for refunds. Non-Disposable containers no bigger than two-liters or a half gallon size are allowed. NOT ALLOWED are gallon thermoses, ice chests of any size, cans, glass or plastic disposable bottles. NO ALCOHOL. Fruit must be sliced or quartered. Hanging or draping of signs, banners or flags on stadium walls or any area of stadium and ground is prohibited. Hand held signs banners or flags that obstruct, endanger or are offensive will be confiscated. Smoking is not permitted inside Folsom Field or Balch Fieldhouse. Fans may smoke outside of the stadium in the southwest or east plazas. Portable stadium seats are allowed as long as they don’t overhang the bleacher or infringe on the seat space of those around you. Rental stadium seats are available near gate 7 and in front of Balch Fieldhouse. Lost, stolen or destroyed tickets are not replaceable. Game times and dates are subject to change without notice. Such changes are not grounds for refunds or exchanges. Holders of tickets to Univ of Colo athletic events agree to abide by Athletic Dept and Univ policies as well as State and Federal Laws.",
                        "childRule":"All persons, including children of any age, MUST have a ticket for admission to the stadium."
                     },
                     "upcomingEvents":{
                        "_total":8,
                        "tmr":6,
                        "ticketmaster":2
                     },
                     "_links":{
                        "self":{
                           "href":"/discovery/v2/venues/KovZpZA1EvaA?locale=en-us"
                        }
                     }
                  }
               ],
               "attractions":[
                  {
                     "name":"Dead & Company",
                     "type":"attraction",
                     "id":"K8vZ917KYU0",
                     "test":false,
                     "url":"https://www.ticketmaster.com/dead-company-tickets/artist/2150235",
                     "locale":"en-us",
                     "externalLinks":{
                        "twitter":[
                           {
                              "url":"https://twitter.com/deadandcompany"
                           }
                        ],
                        "wiki":[
                           {
                              "url":"https://en.wikipedia.org/wiki/Dead_%26_Company"
                           }
                        ],
                        "facebook":[
                           {
                              "url":"https://www.facebook.com/DeadandCompany"
                           }
                        ],
                        "instagram":[
                           {
                              "url":"https://instagram.com/deadandcompany"
                           }
                        ],
                        "musicbrainz":[
                           {
                              "id":"94f8947c-2d9c-4519-bcf9-6d11a24ad006"
                           }
                        ],
                        "homepage":[
                           {
                              "url":"http://www.deadandcompany.com/"
                           }
                        ]
                     },
                     "images":[
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_TABLET_LANDSCAPE_16_9.jpg",
                           "width":1024,
                           "height":576,
                           "fallback":false
                        },
                        {
                           "ratio":"4_3",
                           "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_CUSTOM.jpg",
                           "width":305,
                           "height":225,
                           "fallback":false
                        },
                        {
                           "ratio":"3_2",
                           "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_TABLET_LANDSCAPE_3_2.jpg",
                           "width":1024,
                           "height":683,
                           "fallback":false
                        },
                        {
                           "ratio":"3_2",
                           "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_RETINA_PORTRAIT_3_2.jpg",
                           "width":640,
                           "height":427,
                           "fallback":false
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_EVENT_DETAIL_PAGE_16_9.jpg",
                           "width":205,
                           "height":115,
                           "fallback":false
                        },
                        {
                           "ratio":"3_2",
                           "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_ARTIST_PAGE_3_2.jpg",
                           "width":305,
                           "height":203,
                           "fallback":false
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_RETINA_PORTRAIT_16_9.jpg",
                           "width":640,
                           "height":360,
                           "fallback":false
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/c/fbc/b293c0ad-c904-4215-bc59-8d7f2414dfbc_106141_TABLET_LANDSCAPE_LARGE_16_9.jpg",
                           "width":2048,
                           "height":1152,
                           "fallback":true
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_RECOMENDATION_16_9.jpg",
                           "width":100,
                           "height":56,
                           "fallback":false
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/874/5923c87d-e909-4b12-9231-e4475b0cb874_1282991_RETINA_LANDSCAPE_16_9.jpg",
                           "width":1136,
                           "height":639,
                           "fallback":false
                        }
                     ],
                     "classifications":[
                        {
                           "primary":true,
                           "segment":{
                              "id":"KZFzniwnSyZfZ7v7nJ",
                              "name":"Music"
                           },
                           "genre":{
                              "id":"KnvZfZ7vAeA",
                              "name":"Rock"
                           },
                           "subGenre":{
                              "id":"KZazBEonSMnZfZ7v6A7",
                              "name":"Classic Rock"
                           },
                           "type":{
                              "id":"KZAyXgnZfZ7v7l1",
                              "name":"Group"
                           },
                           "subType":{
                              "id":"KZFzBErXgnZfZ7vA71",
                              "name":"Band"
                           },
                           "family":false
                        }
                     ],
                     "upcomingEvents":{
                        "_total":17,
                        "ticketmaster":17
                     },
                     "_links":{
                        "self":{
                           "href":"/discovery/v2/attractions/K8vZ917KYU0?locale=en-us"
                        }
                     }
                  }
               ]
            }
         },
         {
            "name":"5-Star Theatricals presents Disney's Newsies",
            "type":"event",
            "id":"vvG1iZ4IJEtKCV",
            "test":false,
            "url":"https://www.ticketmaster.com/5star-theatricals-presents-disneys-newsies-thousand-oaks-california-07-25-2020/event/0B005689A7A533B4",
            "locale":"en-us",
            "images":[
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_TABLET_LANDSCAPE_LARGE_16_9.jpg",
                  "width":2048,
                  "height":1152,
                  "fallback":false
               },
               {
                  "ratio":"3_2",
                  "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_ARTIST_PAGE_3_2.jpg",
                  "width":305,
                  "height":203,
                  "fallback":false
               },
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_RETINA_PORTRAIT_16_9.jpg",
                  "width":640,
                  "height":360,
                  "fallback":false
               },
               {
                  "ratio":"4_3",
                  "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_CUSTOM.jpg",
                  "width":305,
                  "height":225,
                  "fallback":false
               },
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_EVENT_DETAIL_PAGE_16_9.jpg",
                  "width":205,
                  "height":115,
                  "fallback":false
               },
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_TABLET_LANDSCAPE_16_9.jpg",
                  "width":1024,
                  "height":576,
                  "fallback":false
               },
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_RETINA_LANDSCAPE_16_9.jpg",
                  "width":1136,
                  "height":639,
                  "fallback":false
               },
               {
                  "ratio":"16_9",
                  "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_RECOMENDATION_16_9.jpg",
                  "width":100,
                  "height":56,
                  "fallback":false
               },
               {
                  "ratio":"3_2",
                  "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_TABLET_LANDSCAPE_3_2.jpg",
                  "width":1024,
                  "height":683,
                  "fallback":false
               },
               {
                  "ratio":"3_2",
                  "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_RETINA_PORTRAIT_3_2.jpg",
                  "width":640,
                  "height":427,
                  "fallback":false
               }
            ],
            "sales":{
               "public":{
                  "startTBD":false
               }
            },
            "dates":{
               "start":{
                  "localDate":"2020-07-25",
                  "localTime":"14:00:00",
                  "dateTime":"2020-07-25T21:00:00Z",
                  "dateTBD":false,
                  "dateTBA":false,
                  "timeTBA":false,
                  "noSpecificTime":false
               },
               "timezone":"America/Los_Angeles",
               "status":{
                  "code":"offsale"
               },
               "spanMultipleDays":false
            },
            "classifications":[
               {
                  "primary":true,
                  "segment":{
                     "id":"KZFzniwnSyZfZ7v7na",
                     "name":"Arts & Theatre"
                  },
                  "genre":{
                     "id":"KnvZfZ7v7l1",
                     "name":"Theatre"
                  },
                  "subGenre":{
                     "id":"KZazBEonSMnZfZ7vAve",
                     "name":"Musical"
                  },
                  "type":{
                     "id":"KZAyXgnZfZ7v7nI",
                     "name":"Undefined"
                  },
                  "subType":{
                     "id":"KZFzBErXgnZfZ7v7lJ",
                     "name":"Undefined"
                  },
                  "family":false
               }
            ],
            "promoter":{
               "id":"494",
               "name":"PROMOTED BY VENUE",
               "description":"PROMOTED BY VENUE / NTL / USA"
            },
            "promoters":[
               {
                  "id":"494",
                  "name":"PROMOTED BY VENUE",
                  "description":"PROMOTED BY VENUE / NTL / USA"
               }
            ],
            "pleaseNote":"Everyone entering the theater must have a paid ticket regardless of age or seating requirements. There are no refunds or exchanges.",
            "priceRanges":[
               {
                  "type":"standard",
                  "currency":"USD",
                  "min":38.0,
                  "max":91.0
               }
            ],
            "seatmap":{
               "staticUrl":"https://maps.ticketmaster.com/maps/geometry/3/event/0B005689A7A533B4/staticImage?type=png&systemId=HOST"
            },
            "ticketLimit":{
               "info":"There is an overall 8 ticket limit for this event."
            },
            "ageRestrictions":{
               "legalAgeEnforced":false
            },
            "_links":{
               "self":{
                  "href":"/discovery/v2/events/vvG1iZ4IJEtKCV?locale=en-us"
               },
               "attractions":[
                  {
                     "href":"/discovery/v2/attractions/K8vZ9173bS0?locale=en-us"
                  }
               ],
               "venues":[
                  {
                     "href":"/discovery/v2/venues/KovZpZAEd1IA?locale=en-us"
                  }
               ]
            },
            "_embedded":{
               "venues":[
                  {
                     "name":"Fred Kavli Theatre- B of A Performing Arts Center,Thousand Oaks",
                     "type":"venue",
                     "id":"KovZpZAEd1IA",
                     "test":false,
                     "url":"https://www.ticketmaster.com/fred-kavli-theatre-b-of-a-tickets-thousand-oaks/venue/90196",
                     "locale":"en-us",
                     "images":[
                        {
                           "ratio":"3_1",
                           "url":"https://s1.ticketm.net/dam/v/002/07fe8bad-a7e2-49f8-a9e0-1a5d27ad0002_379971_SOURCE.jpg",
                           "width":1500,
                           "height":500,
                           "fallback":false
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dbimages/10212v.",
                           "width":205,
                           "height":115,
                           "fallback":false
                        }
                     ],
                     "postalCode":"91362",
                     "timezone":"America/Los_Angeles",
                     "city":{
                        "name":"Thousand Oaks"
                     },
                     "state":{
                        "name":"California",
                        "stateCode":"CA"
                     },
                     "country":{
                        "name":"United States Of America",
                        "countryCode":"US"
                     },
                     "address":{
                        "line1":"2100 E. Thousand Oaks"
                     },
                     "location":{
                        "longitude":"-118.849491",
                        "latitude":"34.175071"
                     },
                     "markets":[
                        {
                           "name":"Los Angeles",
                           "id":"27"
                        }
                     ],
                     "dmas":[
                        {
                           "id":223
                        },
                        {
                           "id":324
                        },
                        {
                           "id":354
                        },
                        {
                           "id":383
                        }
                     ],
                     "social":{
                        "twitter":{
                           "handle":"@tocap"
                        }
                     },
                     "boxOfficeInfo":{
                        "phoneNumberDetail":"(805) 449-ARTS (2787)",
                        "openHoursDetail":"Tue-Sun 12:00noon - 5:00PM Regular Business Hours Box Office open through Curtain on performance days ** Closed Monday **",
                        "acceptedPaymentDetail":"MasterCard, Visa, American Express, Local Checks (check 3 weeks prior to event) or Cash!",
                        "willCallDetail":"Will Call at Civic Auditorium 2 hrs. prior to event. It is recommended that you bring your confirmation number, ID and credit card used to purchase tickets."
                     },
                     "parkingDetail":"Parking garage at the Civic Arts Plaza for $8.00.",
                     "accessibleSeatingDetail":"Accessible seating is available for all performances. Select accessible box or contact TM customer service for more assistance.",
                     "generalInfo":{
                        "childRule":"Some performances offer a discount for children. For all performances EVERYONE needs a ticket, including infants."
                     },
                     "upcomingEvents":{
                        "_total":32,
                        "ticketmaster":32
                     },
                     "_links":{
                        "self":{
                           "href":"/discovery/v2/venues/KovZpZAEd1IA?locale=en-us"
                        }
                     }
                  }
               ],
               "attractions":[
                  {
                     "name":"Newsies (Touring)",
                     "type":"attraction",
                     "id":"K8vZ9173bS0",
                     "test":false,
                     "url":"https://www.ticketmaster.com/newsies-touring-tickets/artist/1984863",
                     "locale":"en-us",
                     "images":[
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_TABLET_LANDSCAPE_LARGE_16_9.jpg",
                           "width":2048,
                           "height":1152,
                           "fallback":false
                        },
                        {
                           "ratio":"3_2",
                           "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_ARTIST_PAGE_3_2.jpg",
                           "width":305,
                           "height":203,
                           "fallback":false
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_RETINA_PORTRAIT_16_9.jpg",
                           "width":640,
                           "height":360,
                           "fallback":false
                        },
                        {
                           "ratio":"4_3",
                           "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_CUSTOM.jpg",
                           "width":305,
                           "height":225,
                           "fallback":false
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_EVENT_DETAIL_PAGE_16_9.jpg",
                           "width":205,
                           "height":115,
                           "fallback":false
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_TABLET_LANDSCAPE_16_9.jpg",
                           "width":1024,
                           "height":576,
                           "fallback":false
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_RETINA_LANDSCAPE_16_9.jpg",
                           "width":1136,
                           "height":639,
                           "fallback":false
                        },
                        {
                           "ratio":"16_9",
                           "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_RECOMENDATION_16_9.jpg",
                           "width":100,
                           "height":56,
                           "fallback":false
                        },
                        {
                           "ratio":"3_2",
                           "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_TABLET_LANDSCAPE_3_2.jpg",
                           "width":1024,
                           "height":683,
                           "fallback":false
                        },
                        {
                           "ratio":"3_2",
                           "url":"https://s1.ticketm.net/dam/a/700/38a2ee5d-5b39-462f-9894-dd68c596b700_21471_RETINA_PORTRAIT_3_2.jpg",
                           "width":640,
                           "height":427,
                           "fallback":false
                        }
                     ],
                     "classifications":[
                        {
                           "primary":true,
                           "segment":{
                              "id":"KZFzniwnSyZfZ7v7na",
                              "name":"Arts & Theatre"
                           },
                           "genre":{
                              "id":"KnvZfZ7v7l1",
                              "name":"Theatre"
                           },
                           "subGenre":{
                              "id":"KZazBEonSMnZfZ7vAve",
                              "name":"Musical"
                           },
                           "type":{
                              "id":"KZAyXgnZfZ7v7nI",
                              "name":"Undefined"
                           },
                           "subType":{
                              "id":"KZFzBErXgnZfZ7v7lJ",
                              "name":"Undefined"
                           },
                           "family":false
                        }
                     ],
                     "upcomingEvents":{
                        "_total":20,
                        "tmr":11,
                        "ticketmaster":9
                     },
                     "_links":{
                        "self":{
                           "href":"/discovery/v2/attractions/K8vZ9173bS0?locale=en-us"
                        }
                     }
                  }
               ]
            }
         }
      ]
   },
   "_links":{
      "first":{
         "href":"/discovery/v2/events.json?countryCode=US&page=0&size=20"
      },
      "self":{
         "href":"/discovery/v2/events.json?countryCode=US"
      },
      "next":{
         "href":"/discovery/v2/events.json?countryCode=US&page=1&size=20"
      },
      "last":{
         "href":"/discovery/v2/events.json?countryCode=US&page=3314&size=20"
      }
   },
   "page":{
      "size":20,
      "totalElements":2,
      "totalPages":1,
      "number":0
   }
};
